// Code generated by goagen v1.2.0, DO NOT EDIT.
//
// API "Todo API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/m0a-mystudy/goa-todo/design
// --out=$(GOPATH)/src/github.com/m0a-mystudy/goa-todo
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// TodoHref returns the resource href.
func TodoHref(todoID interface{}) string {
	paramtodoID := strings.TrimLeftFunc(fmt.Sprintf("%v", todoID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/todos/%v", paramtodoID)
}
