basePath: /api
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateTodoPayload:
    description: A Todo
    example:
      completed: false
      created: 2005-08-21T22:16:40+09:00
      id: 1
      modified: 1979-01-16T08:31:09+09:00
      title: TodoTitleSample
    properties:
      completed:
        default: false
        example: false
        type: boolean
      created:
        default: 1978-06-30T10:00:00+09:00
        description: Date of creation
        example: 2005-08-21T22:16:40+09:00
        format: date-time
        type: string
      id:
        description: ID of Todo
        example: 1
        format: int64
        type: integer
      modified:
        default: 1978-06-30T10:00:00+09:00
        description: Date of last update
        example: 1979-01-16T08:31:09+09:00
        format: date-time
        type: string
      title:
        example: TodoTitleSample
        minLength: 8
        type: string
    required:
    - title
    - completed
    - created
    - modified
    title: CreateTodoPayload
    type: object
  Todo:
    description: A Todo (default view)
    example:
      completed: false
      created: 2005-08-21T22:16:40+09:00
      id: 1
      modified: 1979-01-16T08:31:09+09:00
      title: TodoTitleSample
    properties:
      completed:
        default: false
        example: false
        type: boolean
      created:
        default: 1978-06-30T10:00:00+09:00
        description: Date of creation
        example: 2005-08-21T22:16:40+09:00
        format: date-time
        type: string
      id:
        description: ID of Todo
        example: 1
        format: int64
        type: integer
      modified:
        default: 1978-06-30T10:00:00+09:00
        description: Date of last update
        example: 1979-01-16T08:31:09+09:00
        format: date-time
        type: string
      title:
        example: TodoTitleSample
        minLength: 8
        type: string
    required:
    - title
    - completed
    - created
    - modified
    title: 'Mediatype identifier: application/vnd.todo+json; view=default'
    type: object
  TodoCollection:
    description: TodoCollection is the media type for an array of Todo (default view)
    example:
    - completed: false
      created: 2005-08-21T22:16:40+09:00
      id: 1
      modified: 1979-01-16T08:31:09+09:00
      title: TodoTitleSample
    - completed: false
      created: 2005-08-21T22:16:40+09:00
      id: 1
      modified: 1979-01-16T08:31:09+09:00
      title: TodoTitleSample
    items:
      $ref: '#/definitions/Todo'
    title: 'Mediatype identifier: application/vnd.todo+json; type=collection; view=default'
    type: array
  UpdateTodoPayload:
    example:
      completed: false
      title: Esse autem.
    properties:
      completed:
        example: false
        type: boolean
      title:
        example: Esse autem.
        type: string
    title: UpdateTodoPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: goa study todo api
  title: My Todo
  version: ""
paths:
  /todos:
    get:
      description: Retrieve all todos.
      operationId: todo#list
      produces:
      - application/vnd.todo+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TodoCollection'
        "404":
          description: Not Found
      schemes:
      - http
      summary: list todo
      tags:
      - todo
    post:
      description: Create new todo
      operationId: todo#create
      parameters:
      - description: A Todo
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateTodoPayload'
      produces:
      - application/vnd.todo+json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
      schemes:
      - http
      summary: create todo
      tags:
      - todo
  /todos/{todoID}:
    get:
      description: Retrieve todo within id.
      operationId: todo#show
      parameters:
      - description: todo ID
        in: path
        minimum: 1
        name: todoID
        required: true
        type: integer
      produces:
      - application/vnd.goa.error
      - application/vnd.todo+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Todo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show todo
      tags:
      - todo
    put:
      description: change todo
      operationId: todo#update
      parameters:
      - description: todo ID
        in: path
        minimum: 1
        name: todoID
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateTodoPayload'
      produces:
      - application/vnd.goa.error
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
      schemes:
      - http
      summary: update todo
      tags:
      - todo
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  BadRequest:
    description: Bad Request
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
